name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout DE
        uses: actions/checkout@master
        with:
          path: 'build_de'

      - name: Checkout Symbols
        uses: actions/checkout@master
        with:
          path: 'symbols'
          ref: symbols

      - name: Checkout agbcc
        uses: actions/checkout@master
        with:
          repository: 'pret/agbcc'
          path: 'agbcc'

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
          ./install.sh ../build_de
        working-directory: ./agbcc

      - name: Compare
        run: |
          make -j${nproc} compare_ruby
          make -j${nproc} compare_ruby_rev1
          make -j${nproc} compare_ruby_rev2
          make -j${nproc} compare_sapphire
          make -j${nproc} compare_sapphire_rev1
          make -j${nproc} compare_sapphire_rev2
          make -j${nproc} modern

      - name: Nonmatching
        run: |
          make clean
          make -j${nproc} ruby NONMATCHING=1

      - name: German
        run: |
          sh de_before.sh
          make -j${nproc} compare_ruby_de
          make -j${nproc} compare_ruby_de_debug
          make -j${nproc} compare_ruby_de_rev1
          make -j${nproc} compare_sapphire_de
          make -j${nproc} compare_sapphire_de_debug
          make -j${nproc} compare_sapphire_de_rev1
        working-directory: ./build_de

      - name: Webhook
        if: ${{ github.event_name == 'push' }}
        env:
          CALCROM_DISCORD_WEBHOOK_USERNAME: OK
          CALCROM_DISCORD_WEBHOOK_AVATAR_URL: https://i.imgur.com/38BQHdd.png
          CALCROM_DISCORD_WEBHOOK_URL: ${{ secrets.CALCROM_DISCORD_WEBHOOK_URL }}
        run: sh .github/calcrom/webhook.sh pokeruby

      - name: Move symfiles
        if: ${{ github.event_name == 'push' }}
        run: |
          cp *.sym symbols/
          cp build_de/*.sym symbols/

      - name: Update symfiles
        if: ${{ github.event_name == 'push' }}
        uses: EndBug/add-and-commit@v7
        with:
          branch: symbols
          cwd: "./symbols"
          add: "*.sym"
          message: ${{ github.event.commits[0].message }}
